# Generated by Django 4.0.5 on 2022-06-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_promotion_rename_birth_customer_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
