# Generated by Django 4.0.5 on 2022-07-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
