# Generated by Django 4.0.5 on 2022-07-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_collection_delete_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
