# Generated by Django 4.0.5 on 2022-07-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
